DS - Refactor event form
MareikeFla/community-app pull request #122
Opened 2024-03-23 11:38 UTC by MareikeFla

## Welcome to the biggest useState Festival this side of the digital ocean!

### First of all

The solution shown here contains many useStates. Really many, I know. I came across useReduce during my research and have an irrepressible desire to try it out, HOWEVER I decided to develop this in a separate developer story to make the pull requests clearer. 

### This PR

- I have implemented a logic that prevents the end of an event from being before its start. 
- I have implemented a logic that makes sure that a street has to be entered if a house number has been entered and a link is required if a link description has been entered. 
- I have moved all states and help functions into a separate hook.
- i added a key to check if an event is free of charge and one to check if an event is an online event

### Not this PR

I have moved the following output, originally contained in this DS story, to a separate US - Also to make code review easier: 

- long description should keep paragraphs from the event form long description field
- When long description is too long just the first 600 letters are shown followed by "...mehr" which user can select to see the whole text
- When editing an event long description field has the wrong size and short description character count is wrong

2024-03-25 10:00 UTC, F-Kirchhoff requested changes
Hey Community Team,
quite a complex hook that you created there. It is looking almost fine, I added some suggestions to make the code a bit more readable. Take a look!

2024-03-25 10:00 UTC, F-Kirchhoff commented on lib/useEventForm.js
> +  }
here using the `new FormData()` approach would be really useful, you can save yourself all the `.value` calls.

2024-03-25 10:00 UTC, F-Kirchhoff commented on lib/useEventForm.js
> +    const newEventID = await updateDatabase(eventObject);
using `onSubmit` instead of `updateDatabase` here would follow the general convention and could increase readability of your code. But is optional.

2024-03-25 10:00 UTC, F-Kirchhoff commented on lib/useEventForm.js
> +};
please solve this with styled components, we don't want inline styles in our applications. There should be a solution where you don't hide this functionality in this custom hook but add it directly into the form elements.

2024-03-25 10:00 UTC, F-Kirchhoff commented on lib/useEventForm.js
> +};
please move this into its own file in the lib folder

2024-03-25 10:00 UTC, F-Kirchhoff commented on pages/api/events/index.js
> +        };
you have this logic at two places. You could turn this into a small utility function

2024-03-25 10:07 UTC, MareikeFla commented on lib/useEventForm.js
> +  }
But there's no way to get the FormData object into the structure we want because it's flat, is there? We would still have to create the eventObject according to our structure? That's why we haven't done it so far, because it doesn't offer any added value?
Or do you mean just to improve readability?

2024-03-25 11:03 UTC, MareikeFla commented on lib/useEventForm.js
> +    const newEventID = await updateDatabase(eventObject);
Done

2024-03-25 11:15 UTC, MareikeFla commented on pages/api/events/index.js
> +        };
Done

2024-03-25 12:27 UTC, MareikeFla commented on lib/useEventForm.js
> +};
Today I learned that resizing a textarea can be complex, especially when reducing its size. Browsers handle scrollable content differently, and unlike automatic expansion, shrinking does not adjust the container's height automatically. This maintains the maximum scroll height, making manual resizing necessary to fit the content.

I ended up using one of the many libraries that provide an auto-resizing textarea.

2024-03-25 13:46 UTC, F-Kirchhoff commented on lib/useEventForm.js
> +  }
That is true, I mean that you can use the "data" object from the FormData and Object.fromEntries instead of "eventTarget", then you don't need to access .value all the time. This would improve the readability

2024-03-25 14:02 UTC, F-Kirchhoff commented on lib/useEventForm.js
> +};
the approach itself is fine, but we want to keep our styling with the styled components: here is an example how to do this: https://stackblitz.com/edit/vitejs-vite-fubelm?file=package.json,src/App.jsx,src/App.css&terminal=dev

2024-03-26 12:33 UTC, MareikeFla commented on lib/useEventForm.js
> +  }
done

2024-03-26 12:53 UTC, MareikeFla commented on lib/useEventForm.js
> +};
Hi Felix,

It seems we've had a misunderstanding or I didn't communicated clearly what my problem was. I know how to solve the issue with a styled component, but it doesn't produce the result I want.

The goal is to have a text area that expands as text is entered and shrinks when text is deleted. 
Textarea elements (If I understood it right), unlike divs, don't decrease in size after expanding, as they maintain their maximum height achieved. (You can see that in the example you provided)

Online I found three common solutions:

- Directly manipulate the DOM element, as in the original autogrow function someone in my team wrote. Here, the height is adjusted twice: first to "auto" and then to the new height, allowing the textarea to expand and shrink:

- Create a hidden mirror object that can reduce scroll height (like a div). This mirrors the text and its height is applied to the textarea, allowing it to grow and shrink.

- Use one of the many libraries available for solving this problem.

Yesterday I chose the third option, also because the function wasn't actually part of my story, I only moved it into another file, and I had the feeling doing all this mirror stuff (I had never done) could be big and part of its own DS. 

I now pushed a solution with a mirror object.
If you have any other solutions regarding this, I am happy to take them! :)

2024-03-26 14:21 UTC, JessicaLoers approved these changes
**Hey @MareikeFla** 
I really enjoyed the useState Festival 😁

After the refactor is before the refactor - _there is always something to improve if you dig deep 🏗️  enough._  

For this reason, my comments and the following note are to be understood as optional suggestions. 

**Form control Component**
A generalised form control component can help you encapsulate common behaviors and styles for form fields, such as displaying labels, inputs, and validation messages in a consistent manner across your application. 

Example: Form control Component
```js
export default function ({ label, type = 'text', name, value, onChange, errorMessage, required }) {
  return (
    <div className="form-control">
      <label htmlFor={name}>{label}</label>
      <input
        type={type}
        id={name}
        name={name}
        value={value}
        onChange={onChange}
        required={required}
        aria-required={required ? 'true' : undefined} 
      />
      {errorMessage && <div className="error-message">{errorMessage}</div>}
    </div>
  );
};
```

2024-03-26 14:21 UTC, JessicaLoers commented on components/EventForm/AutoResizingTextArea.js
> +        spellcheck="false"
I guess the `spellCheck` attribute must be in camelCase 🐫

```suggestion
        spellCheck="false"
```

2024-03-26 14:21 UTC, JessicaLoers commented on lib/dateHelpers.js
> +}
**Nice little helpers**

**An egghead 🥚 comments:** 

Consider checking if the input dateString is valid to prevent runtime errors, even if you've already implemented validation in the form. This approach ensures that the helper function can be used safely everywhere.

```suggestion
export function formatDate(dateString) {
  const [year, month, day] = dateString.split("-");
  if (!year || !month || !day) {
    console.error('Invalid date string:', dateString);
    return ''; 
  }
  return `${day}.${month}.${year}`;
}
}
```

2024-03-26 14:21 UTC, JessicaLoers commented on lib/dateHelpers.js
> +};
Another 🥚

Mixing  function declarations and arrow functions isn't inherently bad, but consistency can improve readability and maintainability.


```suggestion
export function getFormattedTodaysDate () {
  const today = new Date();
  const month = `0${today.getMonth() + 1}`.slice(-2);
  const day = `0${today.getDate()}`.slice(-2);
  return `${today.getFullYear()}-${month}-${day}`;
};
```

2024-03-26 14:44 UTC, MareikeFla commented
Thanks @JessicaLoers for your comments and approving!
I am totally aware there is a lot of stuff that could be refactored.
All I tried to do was to stay with my developer story (There is written down what will be refactored) to keep it structured.
That did not work out at all.

2024-03-26 14:52 UTC, MareikeFla commented on components/EventForm/AutoResizingTextArea.js
> +        value={longDescription}
When you use one state, the text inside the textarea is jumping because you are updating the content first and the size of the textarea after it in the useEffect. That is why I use two states. The mirror objects gets the input immediately and has the right height then, after that in the useEffect I can set the set the content and height of the textarea at the same time. 
I found no other way of doing it and have it smooth while typing. 
This is not nice in any way. But it is a solution with styled components.

2024-03-26 14:54 UTC, MareikeFla commented on components/EventForm/AutoResizingTextArea.js
> +        spellcheck="false"
Love the 🐫 !

2024-03-27 10:23 UTC, jana-scheidemann commented
Hey Mareike,
this is my first QA, please be gentle with me :)

Most of your form fields work as you wish, I added 2 test events, unfortunately both of them have an end time that is before start time - this is not what you wanted.

However it is not possible to select a start date in the past - this is what you wanted. as a stressed user that is not paying too much attention, it would be helpful if the past dates would be greyed out or if an alert appears that informs me that the date is in the past and therefore can not be selected.

The Link is also a bit stressful to handle because it needs the "http://" but doesn't offer it (only as a placeholder which is gone as soon as I enter a url - but then I get an error message).

Otherwise your capstone project looks very nice and crazy complex. I am highly impressed.

2024-03-27 14:07 UTC, merged