Us delete and edit event images
MareikeFla/community-app pull request #165
Opened 2024-04-26 09:47 UTC by Bruno0221

2024-04-26 12:20 UTC, F-Kirchhoff requested changes
Hey Comminity Team,
nice work! You are using a good approach to updating your cloudinary data. Please take a look into the suggestions.

2024-04-26 12:20 UTC, F-Kirchhoff commented on pages/api/cloudinary/deleteImage.js
> +    return response.status(405).json({ message: "Method Not Allowed" });
```suggestion
    response.status(405).json({ message: "Method Not Allowed" });
    return
```
Please split this into two lines, since it would suggest that the response object is returned, which should not be the case. calling response.json() itself triggers the response, not returning it.

2024-04-26 12:20 UTC, F-Kirchhoff commented on pages/api/events/[id]/index.js
> +          await cloudinary.v2.uploader.destroy(event.image.public_id);
then set it to true after this line.

2024-04-26 12:20 UTC, F-Kirchhoff commented on pages/api/events/[id]/index.js
> +  }
what if you want to edit the event? This endpoint is already used for only removing the image url. I would suggest you rewrite this part as a general update route. Then you can call this endpoint and pass the event object as it is, only with the image url set to `""`. By this you have a generic update route which you can use to remove the image link.

2024-04-29 08:35 UTC, F-Kirchhoff requested changes

2024-04-29 08:35 UTC, F-Kirchhoff commented on pages/api/events/[id]/index.js
> +
the idea is that you use this specific endpoint (/api/events/[id]) with the "PATCH" method to be able to update `any` information of the event, not just setting the the `image` value to `""`. Instead this endpoint expects a completely new event object inside the `request.body` where any value of the event object could have been changed. This new object can then replace the old event: 

```js
Event.findByIdAndUpdate(id, request.body)
```

On the fontend side, you just need to pass the correct event object if you want just to delete the image entry:

```js 
const newEvent = {
   ...event,
   image: ""
}
fetch(`/api/events/${id}, {
   ...,
   body: JSON.stringify(newEvent)
}
```

By this, your endpoint can function as an "image link remover" and also to update any other information in the event object.

2024-04-29 08:46 UTC, Bruno0221 commented on pages/api/events/[id]/index.js
> +
Thanks for the clarification, I think I get it now. So this more generalized approach for the endpoint is preferable to having entries in the database with empty keys? And I could also pass an empty object instead of an empty string to to the image key if there is no image, right?

2024-04-29 08:53 UTC, F-Kirchhoff commented on pages/api/events/[id]/index.js
> +
In fact, if you pass an empty object, nothing will be changed. The `Update` method of your model updates the mongodb document on a key by key basis. So every key in the object you pass to it will be changed, every other key of the stored mongodb document will be unchanged. So if you pass the object {image: ""} to the method, only the image key of the respective document will be changed to `""`. 

```js
Event.findByIdAndUpdate(id, {image: ""}) // => the document with the id [id] has now a new `image` value of ""
```

2024-04-29 08:53 UTC, F-Kirchhoff commented on pages/api/events/[id]/index.js
> +
if you pass an empty object, not no key will change.

2024-04-29 08:55 UTC, F-Kirchhoff commented on pages/api/events/[id]/index.js
> +
So my suggestion is to use this general approach in order to use this endpoint when you want to update the entire event object, e.g. for an `edit` form.

2024-04-29 10:49 UTC, F-Kirchhoff approved these changes
LGTM 🚀

2024-04-30 07:32 UTC, merged