US - accessibility icons
MareikeFla/community-app pull request #167
Opened 2024-04-29 09:42 UTC by n377i

2024-04-29 13:29 UTC, F-Kirchhoff requested changes
Hi Community Team,

I love what you've done so far. I left some comments for you. It looks like you can take out the useEffects from the EventForm hook, which could help clean things up a bit. Could you check it out? Thanks!

2024-04-29 13:29 UTC, F-Kirchhoff commented on lib/useEventForm.js
> +
You don't need this useEffect, simply use the editEvent.a11yIcons as the initialData of your useState: 
```js
  const [selectedA11yTags, setSelectedA11yTags] = useState( editEvent?.a11yIcons || []);
```

Alternatively you can pass a function to useState and its return value will be the initial state:

```js
  const [selectedA11yTags, setSelectedA11yTags] = useState(() => {
    if (editEvent) {
      return editEvent.a11yIcons || [];
    }
    
    return []
  });
```

2024-04-30 07:41 UTC, n377i commented on lib/useEventForm.js
> +
@F-Kirchhoff Thanks! I decided to go for your first suggestion.

2024-04-30 09:58 UTC, F-Kirchhoff approved these changes
LGTM

2024-05-02 06:58 UTC, merged