Us filter search
MareikeFla/community-app pull request #175
Opened 2024-05-03 06:23 UTC by MareikeFla

2024-05-03 13:06 UTC, onemanwenttomow requested changes
Wow. Lots going on here. Really nice work. I added a few thoughts and suggestions.

2024-05-03 13:29 UTC, MareikeFla commented on components/EventDetail/EventDetail.js
> +      {image && image?.url !== "" ? (
I also thought so, but for some reason doing it like this "{image?.url !== "" ? (" 
will lead to this result:

<img width="1296" alt="Screenshot 2024-05-03 at 15 26 25" src="https://github.com/MareikeFla/community-app/assets/148346025/02f8bcd2-34a2-4003-b730-14762ebad331">

I would be happy to understand why!

2024-05-03 13:30 UTC, MareikeFla commented on components/Search/SearchCard.js
> +                key={i}
fixed it

2024-05-03 13:32 UTC, MareikeFla commented
Hi! Thanks for your review! 
Yes it was quite a ride to do this, there where so many edge cases I did not think of in the beginning.

2024-05-03 13:53 UTC, onemanwenttomow commented on components/EventDetail/EventDetail.js
> +      {image && image?.url !== "" ? (
Hmmm i'm not sure. What is the value of the src of the image in this case?

2024-05-03 13:55 UTC, onemanwenttomow approved these changes
LGTM 🎉

2024-05-06 06:58 UTC, MareikeFla commented on components/EventDetail/EventDetail.js
> +      {image && image?.url !== "" ? (
image is undefined but in my understanding this "image?.url !== """ should check that?

2024-05-06 06:58 UTC, merged